version: "3"
services:
  spider:
    build: ./ChihiroSpider
    networks:
      - chihiro
    depends_on:
      - elasticsearch
      - redis

  search:
    build: ./ChihiroSearch
    ports:
      - "8000:8000"
    networks:
      - chihiro
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    command:
      - sh
      - -c
      - "echo 'y' | ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.6.0/elasticsearch-analysis-ik-7.6.0.zip ;/usr/local/bin/docker-entrypoint.sh"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - chihiro
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - chihiro
    depends_on:
      - elasticsearch

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - chihiro

networks:
  chihiro:
    driver: bridge
